service: apigw-websocket-app
provider:
  name: aws
  stage: dev
resources:
  Resources:
    ChatBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: chat.serverless-barcelona.com
        CorsConfiguration:
          CorsRules:
            - 
              AllowedMethods:
                - GET
              AllowedOrigins:
                - chat.serverless-barcelona.com
              Id: ${self:service}
        WebsiteConfiguration:
          IndexDocument: index.html